-- AlterTable
ALTER TABLE "PomodoroSession" ADD COLUMN     "breakDuration" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "focusedBreakTime" INTEGER NOT NULL DEFAULT 600,
ADD COLUMN     "focusedWorkTime" INTEGER NOT NULL DEFAULT 3000,
ADD COLUMN     "relaxedBreakTime" INTEGER NOT NULL DEFAULT 900,
ADD COLUMN     "relaxedWorkTime" INTEGER NOT NULL DEFAULT 2700,
ADD COLUMN     "standardBreakTime" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN     "standardWorkTime" INTEGER NOT NULL DEFAULT 1500;
